import React from 'react'
import './Account.css'
import Header from './Header'

const TermsOfUse = (props) => {
    return(
        <>
        
        <div className='Transfers DesktopContainer'>
        <div>
        <p><strong>TERMS OF USE</strong></p>
        <p><strong>Last updated&nbsp;January 22, 2021</strong></p>
        <p><strong>AGREEMENT TO TERMS</strong></p>
        <p>These Terms of Use constitute a legally binding agreement made between you, whether personally or on behalf of an entity (“you”, “Customer”, “User”) and&nbsp;SimBull Sports Exchange LLC&nbsp;("Company", “we”, “us”, “our”, “Marketplace”, or “SimBull”), concerning your access to and use of the SimBull website&nbsp;as well as any other media form, media channel, mobile website or mobile application related, linked, or otherwise connected thereto (collectively, the “Site”). The Site provides a closed marketplace for the following goods, products, and/or services:&nbsp;Virtual shares of professional sports team that represent a team mini pennant&nbsp;(the “Marketplace Offerings”). In order to help make the Site a secure environment for the purchase and sale of Marketplace Offerings, all users are required to accept and comply with these Terms of Use, and any other applicable SimBull Sports Exchange LLC policy as each may be amended from time to time. You agree that by accessing the Site and/or the Marketplace Offerings, you have read, understood, and agree to be bound by all of these Terms of Use. Any new SimBull Sports Exchange LLC terms posted on its website shall be effective upon posting and applied to all current and future users. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS OF USE, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SITE AND/OR THE MARKETPLACE OFFERINGS AND YOU MUST DISCONTINUE USE IMMEDIATELY.</p>
        <p>Supplemental terms and conditions or documents that may be posted on the Site from time to time are hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to make changes or modifications to these Terms of Use at any time and for any reason. We will alert you about any changes by updating the “Last updated” date of these Terms of Use, and you waive any right to receive specific notice of each such change. It is your responsibility to periodically review these Terms of Use to stay informed of updates. You will be subject to, and will be deemed to have been made aware of and to have accepted, the changes in any revised Terms of Use by your continued use of the Site after the date such revised Terms of Use are posted. &nbsp;</p>
        <p>The information provided on the Site is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, those persons who choose to access the Site from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.</p>
        <p>The Site is not tailored to comply with industry-specific regulations (Health Insurance Portability and Accountability Act (HIPAA), Federal Information Security Management Act (FISMA), etc.), so if your interactions would be subjected to such laws, you may not use this Site. You may not use the Site in a way that would violate the Gramm-Leach-Bliley Act (GLBA).</p>
        <p>The Site is intended for users who are at least 18 years old. Persons under the age of 18 are not permitted to use or register for the Site or use the Marketplace Offerings. By entering the website you agree that you are above the age of 18.</p>
        <p><strong>INTELLECTUAL PROPERTY RIGHTS</strong></p>
        <p>Unless otherwise indicated, the Site and the Marketplace Offerings are our proprietary property and all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Site (collectively, the “Content”) and the trademarks, service marks, and logos contained therein (the “Marks”) are owned or controlled by us or licensed to us, and are protected by copyright and trademark laws and various other intellectual property rights and unfair competition laws of the United States, international copyright laws, and international conventions. The Content and the Marks are provided on the Site “AS IS” for your information and personal use only. Except as expressly provided in these Terms of Use, no part of the Site or the Marketplace Offerings and no Content or Marks may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission.</p>
        <p>Provided that you are eligible to use the Site, you are granted a limited license to access and use the Site and to download or print a copy of any portion of the Content to which you have properly gained access solely for your personal, non-commercial use. We reserve all rights not expressly granted to you in and to the Site, the Content and the Marks.</p>
        <p><strong>USER REPRESENTATIONS</strong></p>
        <p>By using the Site or the Marketplace Offerings, you represent and warrant that:(1) all registration information you submit will be true, accurate, current, and complete; (2) you will maintain the accuracy of such information and promptly update such registration information as necessary;&nbsp;(3) you have the legal capacity and you agree to comply with these Terms of Use;&nbsp;(4) you are not under the age of 18 years old; (5) you will not access the Site or the Marketplace Offerings through automated or non-human means, whether through a bot, script or otherwise; (6) you will not use the Site for any illegal or unauthorized purpose; and (7) your use of the Site or the Marketplace Offerings will not violate any applicable law or regulation. By using the site you agree that you will not allow third parties to use the site for any illegal purpose. Violation of any part of this section is grounds for immediate Termination of the Service in addition to any other rights or remedies SimBull Sports Exchange may have hereunder.</p>
        <p>If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Site (or any portion thereof).</p>
        <p>You may not use the Site or the Marketplace Offerings for any illegal or unauthorized purpose nor may you, in the use of Marketplace Offerings, violate any laws. Among unauthorized Marketplace Offerings are the following: intoxicants of any sort; illegal drugs or other illegal products; alcoholic beverages; games of chance; and pornography or graphic adult content, images, or other adult products. Postings of any unauthorized products or content may result in immediate termination of your account and a lifetime ban from use of the Site. SimBull may not be held responsible for any illegal actions made by users of the website. You understand and agree that the content of the Site does not contain or constitute representations to be reasonably relied upon, and you agree to hold us harmless from any errors, omissions, or misrepresentations contained within the Site’s content.</p>
        <p><strong>USER REGISTRATION</strong></p>
        <p>You may be required to register with the Site in order to access the Marketplace Offerings. You agree to keep your password confidential and will be responsible for all use of your account and password. We reserve the right to remove, reclaim, or change a username you select if we determine, in our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable. SimBull Sports Exchange is not responsible for unauthorized access to your account and you are responsible for the safety and security of your account. SimBull may not be held responsible for damages to your account, account value, cash deposits, or private information from yourself or a third party.</p>
        <p><strong>MARKETPLACE OFFERINGS</strong></p>
        <p>We make every effort to display as accurately as possible the colors, features, specifications, and details of the Marketplace Offerings available on the Site. However, we do not guarantee that the colors, features, specifications, and details of the Marketplace Offerings will be accurate, complete, reliable, current, or free of other errors, and your electronic display may not accurately reflect the actual colors and details of the products.&nbsp;All Marketplace Offerings are subject to availability, and we cannot guarantee that Marketplace Offerings will be in stock. Certain Marketplace Offerings may be available exclusively online through the Site. Such Marketplace Offerings may have limited quantities.</p>
        <p>We reserve the right to limit the quantities of the Marketplace Offerings offered or available on the Site. All descriptions or pricing of the Marketplace Offerings are subject to change at any time without notice, at our sole discretion. We reserve the right to discontinue any Marketplace Offerings at any time for any reason. We do not warrant that the quality of any of the Marketplace Offerings purchased by you will meet your expectations or that any errors in the Site will be corrected.</p>
        <p>The SimBull Marketplace is a closed Marketplace and all Marketplace Offerings were introduced to the Marketplace through SimBull Sports Exchange. You are not eligible to create your own virtual shares, introduce new shares, sell new shares, or offer to sell new shares, pennants, or any other good in the market that was not permitted by SimBull.</p>
        <p>SimBull Sports Exchange will release and offer new virtual shares, backed by team pennants throughout the year at our discretion. We have the right to limit the offerings in the market and also have the right to increase the Marketplace Offerings at any time and by any amount. All new shares introduced to the market will be sold from SimBull’s account to private users.</p>
        <p><strong>PURCHASES AND PAYMENT</strong></p>
        <p>We accept the following forms of payment:&nbsp;</p>
        <p>- Paypal</p>
        <p>- Venmo</p>
        <p>- Credit Card</p>
        <p>- Debit Card</p>
        <p>You agree to provide current, complete, and accurate purchase and account information for all purchases of the Marketplace Offerings made via the Site. You further agree to promptly update account and payment information, including email address, payment method, and payment card expiration date, so that we can complete your transactions and contact you as needed.</p>
        <p>Taxes, Fees, and Government Charges. Customer agrees to pay any sales, use, property, excise or other taxes, franchise fees, and governmental charges (excluding income taxes), arising under this Agreement, including, without limitation, applicable state property taxes. We may change prices at any time. All payments shall be in&nbsp;U.S. dollars. SimBull is not responsible for documenting, tracking, or paying any sales tax on sales within the Marketplace between users. SimBull is a closed market and thus users are not able to introduce new goods into the market. All transactions in the SimBull market are processed in the closed market and sales tax is not applied in the transaction. It is the users responsibility to pay any necessary sales tax, use tax, income tax, or any other form of taxes or fees to the proper authorities. SimBull is not responsible and may not be held accountable for any taxes or fees the user is required to pay.</p>
        <p>You agree to pay all charges at the prices then in effect for your purchases and any applicable shipping fees, and you authorize us to charge your chosen payment provider for any such amounts upon placing your order.&nbsp;If your order is subject to recurring charges, then you consent to our charging your payment method on a recurring basis without requiring your prior approval for each recurring charge, until such time as you cancel the applicable order.&nbsp;We reserve the right to correct any errors or mistakes in pricing, even if we have already requested or received payment.</p>
        <p>We reserve the right to refuse any order placed through the Site. We may, in our sole discretion, limit or cancel quantities purchased per person, per household, or per order. These restrictions may include orders placed by or under the same customer account, the same payment method, and/or orders that use the same billing or shipping address. We reserve the right to limit or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers, or distributors.</p>
        <p>The physical assets backing virtual shares bought on <a href="http://www.simbull.app" target="_blank" rel="noopener">www.SimBull.app</a> are not FDIC insured, are not bank guaranteed and may lose value. SimBull Sports Exchange LLC does not solicit, recommend, or offer advice on the investment merits of investing in any virtual shares or team pennants offered in the Marketplace. All quotes and orders displayed on <a href="http://www.simbull.app" target="_blank" rel="noopener">www.SimBull.app</a> are from unsolicited orders.&nbsp;</p>
        <p>Virtual shares that represent mini team pennants offered on the SimBull.app platform are speculative and involve a degree of risk. Investing in a virtual share backing a team mini pennant should only be considered by persons who can afford the loss of their entire investment. SimBull is not responsible and may not be held accountable for any decrease in share value, loss of money, or decrease in pennant value.</p>
        <p>This is not an offer to buy or sell securities and SimBull does not offer the ability to buy or sell securities. All marketplace offerings are for a team pennant represented by a virtual share. This is not an offer to gamble or wager money on an event, nor does the SimBull Sports Exchange LLC offer the ability to gamble or wager money on an event. No guarantee is made or implied.</p>
        <p>The user who owns a team pennant represented by a virtual share does not have the right to future win payouts made from SimBull. Win payouts are not guaranteed and win payouts are made at the discretion of SimBull. Ownership of a team pennant represented by a virtual share gives the user the right to the team pennant backing their share and nothing else. All win payouts are optional and voluntary for SimBull. Win payouts are not made by any triggering event, game, or event outside the control of SimBull. All win payouts are at the discretion of SimBull and may be suspended or cancelled at any time.&nbsp;</p>
        <p>If the user has the right to a team pennant represented by a virtual share, at any time they may ask for the delivery of the team pennant. SimBull will verify the validity of the ownership claim and will deliver the team pennant in a reasonable amount of time once a request has been made. At the time of the request, the virtual share representing the team pennant will be destroyed and the user will no longer have the right to the virtual share, or any win payouts connected to the virtual share. Asking for delivery of the team pennant forfeits any right the user has to a virtual share and any future win payouts that may be made to that virtual share.</p>
        <p><strong>RETURN/REFUNDS</strong><strong>&nbsp;POLICY</strong></p>
        <p>All sales are final and no refund will be issued.</p>
        <p><strong>PROHIBITED ACTIVITIES</strong></p>
        <p>You may not access or use the Site for any purpose other than that for which we make the Site available. The Site may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.&nbsp;</p>
        <p>As a user of the Site, you agree not to:</p>
        <p>1.&nbsp;&nbsp;Make any unauthorized use of the Marketplace Offerings, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses.</p>
        <p>2.&nbsp;&nbsp;Use the Site to advertise or offer to sell goods and services.</p>
        <p>3.&nbsp;&nbsp;Circumvent, disable, or otherwise interfere with security-related features of the Site, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Site and/or the Content contained therein.</p>
        <p>4.&nbsp;&nbsp;Engage in unauthorized framing of or linking to the Site.</p>
        <p>5.&nbsp;&nbsp;Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.</p>
        <p>6.&nbsp;&nbsp;Make improper use of our support services or submit false reports of abuse or misconduct.</p>
        <p>7.&nbsp;&nbsp;Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.</p>
        <p>8.&nbsp;&nbsp;Interfere with, disrupt, or create an undue burden on the Site or the networks or services connected to the Site.</p>
        <p>9.&nbsp;&nbsp;Attempt to impersonate another user or person or use the username of another user.</p>
        <p>10.&nbsp;&nbsp;Use any information obtained from the Site in order to harass, abuse, or harm another person.</p>
        <p>11.&nbsp;&nbsp;Use the Marketplace Offerings as part of any effort to compete with us or otherwise use the Site and/or the Content for any revenue-generating endeavor or commercial enterprise.</p>
        <p>12.&nbsp;&nbsp;Decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Site.</p>
        <p>13.&nbsp;&nbsp;Attempt to bypass any measures of the Site designed to prevent or restrict access to the Site, or any portion of the Site.</p>
        <p>14.&nbsp;&nbsp;Harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Marketplace Offerings to you.</p>
        <p>15.&nbsp;&nbsp;Delete the copyright or other proprietary rights notice from any Content.</p>
        <p>16.&nbsp;&nbsp;Copy or adapt the Site’s software, including but not limited to Flash, PHP, HTML, JavaScript, or other code.</p>
        <p>17.&nbsp;&nbsp;Upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with any party’s uninterrupted use and enjoyment of the Site or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Marketplace Offerings.</p>
        <p>18.&nbsp;&nbsp;Upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats (“gifs”), 1×1 pixels, web bugs, cookies, or other similar devices (sometimes referred to as “spyware” or “passive collection mechanisms” or “pcms”).</p>
        <p>19.&nbsp;&nbsp;Except as may be the result of standard search engine or Internet browser usage, use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Site, or using or launching any unauthorized script or other software.</p>
        <p>20.&nbsp;&nbsp;Disparage, tarnish, or otherwise harm, in our opinion, us and/or the Site.</p>
        <p>21.&nbsp;&nbsp;Use the Site in a manner inconsistent with any applicable laws or regulations.</p>
        <p>22.&nbsp;&nbsp;Use a buying agent or purchasing agent to make purchases on the Site.</p>
        <p>23.&nbsp; Perform an illegal action on the website</p>
        <p>These activities, including other activities not mentioned in this section that violate the terms of use or other legal documents from SimBull are grounds for immediate termination and suspension from the site. No refund will be made and your account will be closed.</p>
        <p><strong>USER GENERATED CONTRIBUTIONS</strong></p>
        <p>The Site does not offer users to submit or post content. We may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute, or broadcast content and materials to us or on the Site, including but not limited to text, writings, video, audio, photographs, graphics, comments, suggestions, or personal information or other material (collectively, "Contributions"). Contributions may be viewable by other users of the Site and through third-party websites. As such, any Contributions you transmit may be treated in accordance with the Site Privacy Policy. When you create or make available any Contributions, you thereby represent and warrant that:</p>
        <p>1. &nbsp;The creation, distribution, transmission, public display, or performance, and the accessing, downloading, or copying of your Contributions do not and will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark, trade secret, or moral rights of any third party.2. &nbsp;You are the creator and owner of or have the necessary licenses, rights, consents, releases, and permissions to use and to authorize us, the Site, and other users of the Site to use your Contributions in any manner contemplated by the Site and these Terms of Use.3. &nbsp;You have the written consent, release, and/or permission of each and every identifiable individual person in your Contributions to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of your Contributions in any manner contemplated by the Site and these Terms of Use.4. &nbsp;Your Contributions are not false, inaccurate, or misleading.5. &nbsp;Your Contributions are not unsolicited or unauthorized advertising, promotional materials, pyramid schemes, chain letters, spam, mass mailings, or other forms of solicitation.6. &nbsp;Your Contributions are not obscene, lewd, lascivious, filthy, violent, harassing, libelous, slanderous, or otherwise objectionable (as determined by us).7. &nbsp;Your Contributions do not ridicule, mock, disparage, intimidate, or abuse anyone.8. &nbsp;Your Contributions do not advocate the violent overthrow of any government or incite, encourage, or threaten physical harm against another.9. &nbsp;Your Contributions do not violate any applicable law, regulation, or rule.10. &nbsp;Your Contributions do not violate the privacy or publicity rights of any third party.11. &nbsp;Your Contributions do not contain any material that solicits personal information from anyone under the age of 18 or exploits people under the age of 18 in a sexual or violent manner.12. &nbsp;Your Contributions do not violate any applicable law concerning child pornography, or otherwise intended to protect the health or well-being of minors.13. &nbsp;Your Contributions do not include any offensive comments that are connected to race, national origin, gender, sexual preference, or physical handicap.14. &nbsp;Your Contributions do not otherwise violate, or link to material that violates, any provision of these Terms of Use, or any applicable law or regulation.</p>
        <p>Any use of the Site or the Marketplace Offerings in violation of the foregoing violates these Terms of Use and may result in, among other things, termination or suspension of your rights to use the Site and the Marketplace Offerings.</p>
        <p><strong>CONTRIBUTION LICENSE</strong></p>
        <p>You and the Site agree that we may access, store, process, and use any information and personal data that you provide following the terms of the Privacy Policy and your choices (including settings).</p>
        <p>By submitting suggestions or other feedback regarding the Site, you agree that we can use and share such feedback for any purpose without compensation to you.</p>
        <p>We do not assert any ownership over your Contributions. You retain full ownership of all of your Contributions and any intellectual property rights or other proprietary rights associated with your Contributions. We are not liable for any statements or representations in your Contributions provided by you in any area on the Site. You are solely responsible for your Contributions to the Site and you expressly agree to exonerate us from any and all responsibility and to refrain from any legal action against us regarding your Contributions.</p>
        <p><strong>SUBMISSIONS</strong></p>
        <p>You acknowledge and agree that any questions, comments, suggestions, ideas, feedback, or other information regarding the Site or the Marketplace Offerings ("Submissions") provided by you to us are non-confidential and shall become our sole property. We shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use and dissemination of these Submissions for any lawful purpose, commercial or otherwise, without acknowledgment or compensation to you. You hereby waive all moral rights to any such Submissions, and you hereby warrant that any such Submissions are original with you or that you have the right to submit such Submissions. You agree there shall be no recourse against us for any alleged or actual infringement or misappropriation of any proprietary right in your Submissions.&nbsp;</p>
        <p><strong>ADVERTISERS</strong></p>
        <p>We allow advertisers to display their advertisements and other information in certain areas of the Site, such as sidebar advertisements or banner advertisements. If you are an advertiser, you shall take full responsibility for any advertisements you place on the Site and any services provided on the Site or products sold through those advertisements. Further, as an advertiser, you warrant and represent that you possess all rights and authority to place advertisements on the Site, including, but not limited to, intellectual property rights, publicity rights, and contractual rights.&nbsp;We simply provide the space to place such advertisements, and we have no other relationship with advertisers.</p>
        <p><strong>SITE MANAGEMENT</strong></p>
        <p>We reserve the right, but not the obligation, to: (1) monitor the Site for violations of these Terms of Use; (2) take appropriate legal action against anyone who, in our sole discretion, violates the law or these Terms of Use, including without limitation, reporting such user to law enforcement authorities; (3) in our sole discretion and without limitation, refuse, restrict access to, limit the availability of, or disable (to the extent technologically feasible) any of your Contributions or any portion thereof; (4) in our sole discretion and without limitation, notice, or liability, to remove from the Site or otherwise disable all files and content that are excessive in size or are in any way burdensome to our systems; and (5) otherwise manage the Site in a manner designed to protect our rights and property and to facilitate the proper functioning of the Site and the Marketplace Offerings.</p>
        <p><strong>PRIVACY POLICY</strong></p>
        <p>We care about data privacy and security. By using the Site or the Marketplace Offerings, you agree to be bound by our Privacy Policy posted on the Site, which is incorporated into these Terms of Use. Please be advised the Site and the Marketplace Offerings are hosted in&nbsp;the&nbsp;United States. If you access the Site or the Marketplace Offerings from any other region of the world with laws or other requirements governing personal data collection, use, or disclosure that differ from applicable laws in&nbsp;the&nbsp;United States, then through your continued use of the Site, you are transferring your data to&nbsp;the&nbsp;United States, and you agree to have your data transferred to and processed in&nbsp;the&nbsp;United States.&nbsp;</p>
        <p><strong>TERM AND TERMINATION</strong></p>
        <p>These Terms of Use shall remain in full force and effect while you use the Site. WITHOUT LIMITING ANY OTHER PROVISION OF THESE TERMS OF USE, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE SITE AND THE MARKETPLACE OFFERINGS (INCLUDING BLOCKING CERTAIN IP ADDRESSES), TO ANY PERSON FOR ANY REASON OR FOR NO REASON, INCLUDING WITHOUT LIMITATION FOR BREACH OF ANY REPRESENTATION, WARRANTY, OR COVENANT CONTAINED IN THESE TERMS OF USE OR OF ANY APPLICABLE LAW OR REGULATION. WE MAY TERMINATE YOUR USE OR PARTICIPATION IN THE SITE AND THE MARKETPLACE OFFERINGS OR DELETE&nbsp;YOUR ACCOUNT AND&nbsp;ANY CONTENT OR INFORMATION THAT YOU POSTED AT ANY TIME, WITHOUT WARNING, IN OUR SOLE DISCRETION.&nbsp;</p>
        <p>If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or borrowed name, or the name of any third party, even if you may be acting on behalf of the third party. In addition to terminating or suspending your account, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress.</p>
        <p><strong>MODIFICATIONS AND INTERRUPTIONS</strong></p>
        <p>We reserve the right to change, modify, or remove the contents of the Site at any time or for any reason at our sole discretion without notice. However, we have no obligation to update any information on our Site. We also reserve the right to modify or discontinue all or part of the Marketplace Offerings without notice at any time. We will not be liable to you or any third party for any modification, price change, suspension, or discontinuance of the Site or the Marketplace Offerings. &nbsp;</p>
        <p>We cannot guarantee the Site and the Marketplace Offerings will be available at all times. We may experience hardware, software, or other problems or need to perform maintenance related to the Site, resulting in interruptions, delays, or errors. We reserve the right to change, revise, update, suspend, discontinue, or otherwise modify the Site or the Marketplace Offerings at any time or for any reason without notice to you. You agree that we have no liability whatsoever for any loss, damage, or inconvenience caused by your inability to access or use the Site or the Marketplace Offerings during any downtime or discontinuance of the Site or the Marketplace Offerings. Nothing in these Terms of Use will be construed to obligate us to maintain and support the Site or the Marketplace Offerings or to supply any corrections, updates, or releases in connection therewith.</p>
        <p><strong>GOVERNING LAW</strong></p>
        <p>These Terms of Use and your use of the Site and the Marketplace Offerings are governed by and construed in accordance with the laws of&nbsp;the State of&nbsp;Minnesota&nbsp;applicable to agreements made and to be entirely performed within&nbsp;the State of&nbsp;Minnesota,&nbsp;without regard to its conflict of law principles.</p>
        <p><strong>DISPUTE RESOLUTION</strong></p>
        <p><strong>Binding Arbitration</strong></p>
        <p>If the Parties are unable to resolve a Dispute through informal negotiations, the Dispute (except those Disputes expressly excluded below) will be finally and exclusively resolved through binding arbitration. YOU UNDERSTAND THAT WITHOUT THIS PROVISION, YOU WOULD HAVE THE RIGHT TO SUE IN COURT AND HAVE A JURY TRIAL. The arbitration shall be commenced and conducted under the Commercial Arbitration Rules of the American Arbitration Association ("AAA") and, where appropriate, the AAA’s Supplementary Procedures for Consumer Related Disputes ("AAA Consumer Rules"), both of which are available at the AAA website:&nbsp;<a href="http://www.adr.org" target="_blank" rel="noopener"><span style={{color: '#0000ff'}}>www.adr.org</span></a>. Your arbitration fees and your share of arbitrator compensation shall be governed by the AAA Consumer Rules and, where appropriate, limited by the AAA Consumer Rules.&nbsp;The arbitration may be conducted in person, through the submission of documents, by phone, or online. The arbitrator will make a decision in writing, but need not provide a statement of reasons unless requested by either Party. The arbitrator must follow applicable law, and any award may be challenged if the arbitrator fails to do so. Except where otherwise required by the applicable AAA rules or applicable law, the arbitration will take place in&nbsp;United States,&nbsp;Minnesota. Except as otherwise provided herein, the Parties may litigate in court to compel arbitration, stay proceedings pending arbitration, or to confirm, modify, vacate, or enter judgment on the award entered by the arbitrator.</p>
        <p>If for any reason, a Dispute proceeds in court rather than arbitration, the Dispute shall be commenced or prosecuted in the&nbsp;state and federal courts&nbsp;located in&nbsp;United States,&nbsp;Minnesota, and the Parties hereby consent to, and waive all defenses of lack of personal jurisdiction, and forum non conveniens with respect to venue and jurisdiction in such&nbsp;state and federal courts. Application of the United Nations Convention on Contracts for the International Sale of Goods and the the Uniform Computer Information Transaction Act (UCITA) is excluded from these Terms of Use.</p>
        <p>If this provision is found to be illegal or unenforceable, then neither Party will elect to arbitrate any Dispute falling within that portion of this provision found to be illegal or unenforceable, and such Dispute shall be decided by a court of competent jurisdiction within the courts listed for jurisdiction above, and the Parties agree to submit to the personal jurisdiction of that court.</p>
        <p><strong>Restrictions</strong></p>
        <p>The Parties agree that any arbitration shall be limited to the Dispute between the Parties individually. To the full extent permitted by law, (a) no arbitration shall be joined with any other proceeding; (b) there is no right or authority for any Dispute to be arbitrated on a class-action basis or to utilize class action procedures; and (c) there is no right or authority for any Dispute to be brought in a purported representative capacity on behalf of the general public or any other persons.</p>
        <p><strong>Exceptions to Arbitration</strong></p>
        <p>The Parties agree that the following Disputes are not subject to the above provisions concerning binding arbitration: (a) any Disputes seeking to enforce or protect, or concerning the validity of, any of the intellectual property rights of a Party; (b) any Dispute related to, or arising from, allegations of theft, piracy, invasion of privacy, or unauthorized use; and (c) any claim for injunctive relief. If this provision is found to be illegal or unenforceable, then neither Party will elect to arbitrate any Dispute falling within that portion of this provision found to be illegal or unenforceable and such Dispute shall be decided by a court of competent jurisdiction within the courts listed for jurisdiction above, and the Parties agree to submit to the personal jurisdiction of that court.</p>
        <p><strong>CORRECTIONS</strong></p>
        <p>There may be information on the Site that contains typographical errors, inaccuracies, or omissions that may relate to the Marketplace Offerings, including descriptions, pricing, availability, and various other information. We reserve the right to correct any errors, inaccuracies, or omissions and to change or update the information on the Site at any time, without prior notice.</p>
        <p><strong>DISCLAIMER</strong></p>
        <p>THE SITE AND THE MARKETPLACE OFFERINGS ARE PROVIDED ON AN AS-IS AND AS-AVAILABLE BASIS. YOU AGREE THAT YOUR USE OF THE SITE AND OUR SERVICES WILL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SITE AND THE MARKETPLACE OFFERINGS AND YOUR USE THEREOF, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE MAKE NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE SITE’S CONTENT OR THE CONTENT OF ANY WEBSITES LINKED TO THE SITE AND WE WILL ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY (1) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT AND MATERIALS, (2) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SITE, (3) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (4) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SITE OR THE MARKETPLACE OFFERINGS, (5) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SITE BY ANY THIRD PARTY, AND/OR (6) ANY ERRORS OR OMISSIONS IN ANY CONTENT AND MATERIALS OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SITE. WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SITE, ANY HYPERLINKED WEBSITE, OR ANY WEBSITE OR MOBILE APPLICATION FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND ANY THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</p>
        <p>The physical assets backing virtual shares bought on <a href="http://www.simbull.app" target="_blank" rel="noopener">www.SimBull.app</a> are not FDIC insured, are not bank guaranteed and may lose value. SimBull Sports Exchange LLC does not solicit, recommend, or offer advice on the investment merits of investing in any virtual shares offered on the SimBull.app platform. All quotes and orders displayed on <a href="http://www.simbull.app" target="_blank" rel="noopener">www.SimBull.app</a> are from unsolicited orders.&nbsp;</p>
        <p>Virtual shares that represent mini team pennants offered on the SimBull.app platform are speculative and involve a degree of risk. Investing in a virtual share backing a team mini pennant should only be considered by persons who can afford the loss of their entire investment.&nbsp;</p>
        <p>This is not an offer to buy or sell securities. This is not an offer to gamble or wager money on an event, nor does the SimBull Sports Exchange LLC offer the ability to gamble or wager money on an event. No guarantee is made or implied.</p>
        <p>Users of <a href="http://www.simbull.app" target="_blank" rel="noopener">www.SimBull.app</a> owned by SimBull Sports Exchange LLC are responsible for possible tax consequences in the United States or their local jurisdiction. As such, users should consult your own tax advisor regarding possible tax consequences of owning and disposing virtual shares backed by a physical asset and payouts. SimBull Sports Exchange LLC is not liable for tax consequences of the user’s profit or loss on the website <a href="http://www.simbull.app" target="_blank" rel="noopener">www.SimBull.app</a>. SimBull Sports Exchange LLC is not liable and may not be held responsible for tax consequences of the user’s sale or purchase of team pennants in the Marketplace.</p>
        <p><strong>LIMITATIONS OF LIABILITY</strong></p>
        <p>IN NO EVENT WILL WE OR OUR DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT, LOST REVENUE, LOSS OF DATA, TAX CONSEQUENCES, TAX PENALITIES, OR OTHER DAMAGES ARISING FROM YOUR USE OF THE SITE OR THE MARKETPLACE OFFERINGS, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.&nbsp;NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO&nbsp;THE AMOUNT PAID, IF ANY, BY YOU TO US&nbsp;DURING THE&nbsp;ONE (1) MONTH PERIOD PRIOR TO ANY CAUSE OF ACTION ARISING. CERTAIN US STATE LAWS AND INTERNATIONAL LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.</p>
        <p><strong>Miscellaneous</strong></p>
        <p>These terms and conditions and any related, executed Service Order(s) constitute the entire Agreement with respect to the Marketplace. These terms and conditions supersedes all prior understandings, promises and undertakings, if any, made orally or in writing by or on behalf of the parties with respect to the subject matter of this Service Agreement. Customer acknowledges and agrees that no oral representations by any SimBull employee can be relied upon to supersede any term stated in the SimBull Terms of Use agreed to by the Customer. If the terms of the SimBull contract conflict with any alleged oral representation made by any SimBull employee, the SimBull Terms of Use supersedes all prior promises and understandings.</p>
        <p><strong>INDEMNIFICATION</strong></p>
        <p>In addition to its specific indemnification responsibilities set forth elsewhere in these Terms and Conditions and as permissible under applicable law, Customer agrees, at its own expense, to indemnify, defend and hold harmless SimBull and its directors, employees, representatives, officers and agents, (the "Indemnified Parties") against any and all claims, liabilities, lawsuits, damages, losses, judgments, costs, fees and expenses incurred by SimBull Indemnified Parties, including but not limited to, reasonable attorneys' fees and court costs incurred by SimBull Indemnified Parties provided under these terms and conditions, to the full extent that such arise from Customer's misrepresentation with regard to or noncompliance with the terms of the Service and any or all Service Orders, Customer's failure to comply with applicable law, and/or Customer's negligence or willful misconduct. SimBull Indemnified Parties shall have the right but not the obligation to participate in the defense of the claim at Customer‘s cost and Customer agrees to cooperate with SimBull Indemnified Parties in such case.&nbsp;</p>
        <p><strong>USER DATA</strong></p>
        <p>We will maintain certain data that you transmit to the Site for the purpose of managing the performance of the Marketplace Offerings, as well as data relating to your use of the Marketplace Offerings. Although we perform regular routine backups of data, you are solely responsible for all data that you transmit or that relates to any activity you have undertaken using the Marketplace Offerings. You agree that we shall have no liability to you for any loss or corruption of any such data, and you hereby waive any right of action against us arising from any such loss or corruption of such data.</p>
        <p><strong>ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES</strong></p>
        <p>Visiting the Site, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications, and you agree that all agreements, notices, disclosures, and other communications we provide to you electronically, via email and on the Site, satisfy any legal requirement that such communication be in writing. YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS, AND OTHER RECORDS, AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES, AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED BY US OR VIA THE SITE. You hereby waive any rights or requirements under any statutes, regulations, rules, ordinances, or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records, or to payments or the granting of credits by any means other than electronic means.&nbsp;</p>
        <p><strong>CALIFORNIA USERS AND RESIDENTS</strong></p>
        <p>If any complaint with us is not satisfactorily resolved, you can contact the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs in writing at 1625 North Market Blvd., Suite N 112, Sacramento, California 95834 or by telephone at (800) 952-5210 or (916) 445-1254.</p>
        <p><strong>MISCELLANEOUS</strong></p>
        <p>These Terms of Use and any policies or operating rules posted by us on the Site or in respect to the Marketplace Offerings constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce any right or provision of these Terms of Use shall not operate as a waiver of such right or provision. These Terms of Use operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time. We shall not be responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control. If any provision or part of a provision of these Terms of Use is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these Terms of Use and does not affect the validity and enforceability of any remaining provisions. There is no joint venture, partnership, employment or agency relationship created between you and us as a result of these Terms of Use or use of the Marketplace Offerings. You agree that these Terms of Use will not be construed against us by virtue of having drafted them. You hereby waive any and all defenses you may have based on the electronic form of these Terms of Use and the lack of signing by the parties hereto to execute these Terms of Use.</p>
        <p><strong>Notices</strong></p>
        <p>Any notices to be given shall be validly given or served only if in writing and sent by nationally recognized overnight delivery service or certified mail, return receipt requested, to the following addresses:If to SimBull:&nbsp;</p>
        <p>SimBull Sports Exchange LLC1400 Laurel Ave. APT 911</p>
        <p>Minneapolis, MN 55403&nbsp;</p>
        <p>Each party may change its respective address(es) for legal notice by providing notice to the other party.&nbsp;</p>
        <p><strong>CONTACT US</strong></p>
        <p>In order to resolve a complaint regarding the Site or the Marketplace Offerings or to receive further information regarding use of the Site or the Marketplace Offerings, please contact us at:&nbsp;</p>
        <p><strong>SimBull Sports Exchange LLC</strong></p>
        <p><strong>1400 Laurel Ave.</strong></p>
        <p><strong>APT W911</strong></p>
        <p><strong>Minneapolis,&nbsp;MN&nbsp;55403</strong></p>
        <p><strong>United States</strong></p>
        <p><strong>Phone:&nbsp;3198996223</strong></p>
        <p><strong>customer-service@simbull.app</strong></p>
      </div>
        </div>
        </>
    )
}

export default TermsOfUse